TimeKeeping Interval
HyperityLTD/scp087b pull request #40
Opened 2023-05-05 22:38 UTC by thaddli

Opening the current branch for preliminary reasons. Current implementation WILL be changed (Don't want to add anything more to World), current commit is just a PoC before moving it around easily. Using accumulator to reset stats roughly each second.

2023-05-05 23:12 UTC, Saalvage commented on Src/Timing/TimeMaster.cpp
> +        child.time = (u64) 0;
Cast is unnecessary here

2023-05-09 20:44 UTC, thaddli commented
New commit has StatWorld basically keep it's own form of the ticker, currently at one second. Frees up World bloat.

2023-05-11 01:27 UTC, Saalvage requested changes
Minor stuff aside from the incorrect handling of nested timers.

2023-05-11 01:27 UTC, Saalvage commented on Src/Timing/TimeMaster.cpp
> +        child.time = 0;
You need to descend the entire tree here.

It only works when summing because each Timer encloses all of its children (it starts before the first and ends after the last).

2023-05-11 01:27 UTC, Saalvage commented on Src/World/StatWorld.h
> +#include<chrono>
Missing space after `include`.

2023-05-11 01:27 UTC, Saalvage commented on Src/World/StatWorld.h
> +		static constexpr float TIME_INTERVAL = CLOCK_TIME_SECOND * 1;
Not a fan of the duplication here, if you can't find a better way just have a header containing a static class with the shared information.

2023-05-11 01:27 UTC, Saalvage commented on Src/World/StatWorld.h
> +		PGE::u64 timePast = 0;
Pretty sure it should be `timePassed` in this context, since it's about time that has passed, and not past some time. Also since it's in ticks `ticksPassed` might be better. `tickAccu` like in Ticker.h also wouldn't be that bad.

2023-05-11 22:19 UTC, thaddli commented on Src/World/StatWorld.h
> +		static constexpr float TIME_INTERVAL = CLOCK_TIME_SECOND * 1;
Could be resolved but may not be due to poor practice/understanding. Added namespace containing TimeInfo.

2023-05-12 00:34 UTC, Saalvage requested changes
Despite the PR literally doing nothing in practice atm (please fix) we're getting there stylistically.

2023-05-12 00:34 UTC, Saalvage commented on Src/Timing/Ticker.h
> +		std::chrono::time_point<std::chrono::steady_clock> prev;
Not using `Clock` from the header specifically made for sharing the exact clock we want to use consistently?

2023-05-12 00:34 UTC, Saalvage commented on Src/World/StatWorld.h
> +		std::chrono::time_point<std::chrono::steady_clock> priorTime;
Same here, use the `Clock` we defined in the namespace for exactly this purpose!!

2023-05-12 00:34 UTC, Saalvage commented on Src/World/StatWorld.h
> +		std::chrono::time_point<std::chrono::steady_clock> priorTime;
(This will allow you to cut down on the `include`s)

2023-05-12 00:34 UTC, Saalvage commented on Src/Timing/TimeMaster.cpp
> +}
You forgot to actually reset the value somewhere.

2023-05-12 00:34 UTC, Saalvage commented on Src/Timing/TimeMaster.h
> +		void resetInterval(Time& head);
~~This can be merged into one method (e.g. by using a pointer argument with default value `nullptr` and overriding nullptr with top if present). Would reduce duplication to some degree but would also be kind of ugly. Your call.~~

2023-05-12 00:34 UTC, Saalvage commented on Src/Timing/TimeMaster.h
> +		void resetInterval(Time& head);
On second thought, this should be a method of `Time`. Then the one in this class just calls it on `top`.

2023-05-12 00:34 UTC, Saalvage commented on Src/World/StatWorld.cpp
> +	priorTime = currTime;
I don't really like how this code is duplicated here and in `World`. I have not looked too deep into it but I feel like a sensible abstraction can be made that includes just what we need. This new class would also be where the `TimeInfo` stuff can go!

2023-05-12 22:37 UTC, thaddli commented on Src/World/StatWorld.cpp
> +	priorTime = currTime;
May misunderstand the comment but did remove the ```World``` function. Can definitely still look into abstraction but just misunderstanding on my end!

2023-05-13 00:38 UTC, Saalvage requested changes
Just minor stuff

2023-05-13 00:38 UTC, Saalvage commented on Src/Timing/Time.cpp
> +    if (!children.empty()) {
What does this check accomplish?

2023-05-13 00:38 UTC, Saalvage commented on Src/Timing/Time.h
>  #endif // B_TIME_H_INCLUDED
Not your fault, but while we're at it I'd like to remove the missing newline at the end of this file.

2023-05-13 00:38 UTC, Saalvage commented on Src/Timing/TimeMaster.cpp
> +    for (auto& [_, child] : top.children) {
The loop here is pointless. One of the reasons for moving the main body of the recursive apparatus to the `Time` class was to avoid this duplication. Just call `resetTime` on `top`.

2023-05-13 00:38 UTC, Saalvage commented on Src/Timing/TimeMaster.h
> +#include "TimeInfo.h"
Can be moved to implementation file.

2023-05-13 00:38 UTC, Saalvage commented on Src/World/StatWorld.cpp
> +	priorTime = currTime;
Ticker.cpp contains pretty much a straight up copy of this code.
It's the only other place that requires access to `TimeInfo`.
This should make for something great to abstract out, but should probably wait for now since I want to get this merged first.

2023-05-13 19:55 UTC, Saalvage approved these changes

2023-05-13 19:55 UTC, merged